### ISSUE TITLE
关于论文中的V-reg valence 任务中，评价指标选择用皮尔逊相关系数的疑惑

### ISSUE THREAD

**Issue by lindiefan** [lzw108/EmoLLMs#1]
我注意到在论文中，您选择了以皮尔逊相关系数来作为V-reg valence 任务的评价指标，但是这是令我疑惑的，V-reg valence任务不是输出一个值（给定一条推文，确定最能代表推文作者心理状态的情感或价值观（V）的强度 - 介于0（最消极）和1（最积极）之间的实值分数；），那这个值怎么能用相关系数来评价呢？这就很让人疑惑了，请问您在处理这一块内容的时候是如何思考的

**Comment by lindiefan** [comment]
我提这个问题，不是为了挑刺，就是单纯的想和作者讨论一下，我目前也面临选择评价指标的困难，想听听作者的想法

**Comment by lzw108** [comment]
模型预测的值与原始数据中的golden标签进行评估
